export interface BrandDefinition {
  slug: string;
  name: string;
  bengaliName: string;
  searchQuery: string;
  titleEn: string;
  titleBn: string;
  descEn: string;
  descBn: string;
  badgeEn: string;
  badgeBn: string;
  summaryEn: string;
  summaryBn: string;
}

export const POPULAR_BRANDS: readonly BrandDefinition[] = [
  {
    slug: 'radhuni',
    name: 'Radhuni',
    bengaliName: 'রাঁধুনী',
    searchQuery: 'Radhuni',
    titleEn: 'Radhuni Spices & Cooking Ingredients in Chattogram | Lucky Store',
    titleBn: 'রাঁধুনী মসলা ও রান্নার সামগ্রী চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Buy authentic Radhuni spices, mustard oil & recipe mixes at Lucky Store in Chawkbazar, Chattogram. Same-day delivery with 100% doorstep inspection.',
    descBn: 'চট্টগ্রামের চকবাজারে লাকি স্টোরে আসল রাঁধুনী মসলা, সরিষার তেল ও গুঁড়া মসলা কিনুন। ক্যাশ অন ডেলিভারি ও ডোরস্টেপ চেকিং সুবিধা।',
    badgeEn: 'Pure Spices & Oils',
    badgeBn: 'খাঁটি মসলা ও তেল',
    summaryEn: 'Explore authentic Radhuni ground spices, turmeric, chili, coriander, meat curry mixes, and pure kachi ghani mustard oil delivered same-day in Chattogram.',
    summaryBn: 'রাঁধুনী খাঁটি গুঁড়া মসলা, হলুদ, মরিচ, ধনিয়া, বিরিয়ানি মিক্স ও সরিষার তেল ঘরে বসে অনলাইনে অর্ডার করুন।',
  },
  {
    slug: 'aarong',
    name: 'Aarong',
    bengaliName: 'আড়ং',
    searchQuery: 'Aarong',
    titleEn: 'Aarong Dairy, Milk & Pure Ghee in Chattogram | Lucky Store',
    titleBn: 'আড়ং ডেইরি, দুধ ও খাঁটি ঘি চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Shop fresh Aarong liquid milk, standardized milk, yogurt & pure cow milk ghee from Lucky Store in Chattogram. Fast doorstep grocery delivery.',
    descBn: 'চট্টগ্রামে লাকি স্টোর থেকে টাটকা আড়ং তরল দুধ, প্যাকেটজাত দুধ ও খাঁটি গাওয়া ঘি অর্ডার করুন। দ্রুত হোম ডেলিভারি।',
    badgeEn: 'Fresh Dairy & Ghee',
    badgeBn: 'টাটকা ডেইরি ও ঘি',
    summaryEn: 'Wholesome Aarong dairy products including pure cow milk ghee, pasteurized liquid milk, and fresh dairy staples delivered cold to your home.',
    summaryBn: 'আড়ং এর সেরা মানের গাওয়া ঘি ও প্যাকেটজাত খাঁটি তরল দুধ এখন লাকি স্টোরে সহজলভ্য।',
  },
  {
    slug: 'rupchanda',
    name: 'Rupchanda',
    bengaliName: 'রূপচাঁদা',
    searchQuery: 'Rupchanda',
    titleEn: 'Rupchanda Fortified Soybean Oil in Chattogram | Lucky Store',
    titleBn: 'রূপচাঁদা ফর্টিফাইড সয়াবিন তেল চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Check current Rupchanda 1L, 2L & 5L soybean oil prices in Chattogram. Order online from Lucky Store with Cash on Delivery and doorstep inspection.',
    descBn: 'চট্টগ্রামে রূপচাঁদা সয়াবিন তেলের বর্তমান বাজারদর দেখে অনলাইনে অর্ডার করুন। ক্যাশ অন ডেলিভারি ও দ্রুত ডেলিভারি।',
    badgeEn: 'Vitamin A Fortified',
    badgeBn: 'ভিটামিন এ সমৃদ্ধ',
    summaryEn: 'Leading edible oil brand Rupchanda Vitamin A fortified soybean oil and premium mustard oil available at transparent displayed prices.',
    summaryBn: 'রূপচাঁদা ভিটামিন এ সমৃদ্ধ বিশুদ্ধ সয়াবিন তেল ও খাঁটি সরিষার তেল ঘরে বসেই ডেলিভারি নিন।',
  },
  {
    slug: 'teer',
    name: 'Teer',
    bengaliName: 'তীর',
    searchQuery: 'Teer',
    titleEn: 'Teer Soybean Oil, Atta & Essentials in Chattogram | Lucky Store',
    titleBn: 'তীর সয়াবিন তেল, আটা ও ময়দা চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Shop Teer fortified soybean oil, whole wheat atta, maida & suji in Chattogram at displayed bazaar prices from Lucky Store.',
    descBn: 'লাকি স্টোর থেকে তীর সয়াবিন তেল, লাল আটা, ময়দা ও সুজি বর্তমান বাজারদরে ঘরে বসেই অর্ডার করুন।',
    badgeEn: 'Daily Kitchen Staples',
    badgeBn: 'নিত্য প্রয়োজনীয় খাদ্যপণ্য',
    summaryEn: 'High quality Teer fortified cooking oil, premium flour, and baking essentials delivered directly from Chawkbazar.',
    summaryBn: 'তীর ব্যান্ডের ফর্টিফাইড ভোজ্য তেল এবং উন্নত মানের আটা ও ময়দা কিনুন সাশ্রয়ী মূল্যে।',
  },
  {
    slug: 'fresh',
    name: 'Fresh',
    bengaliName: 'ফ্রেশ',
    searchQuery: 'Fresh',
    titleEn: 'Fresh Sugar, Edible Oil & Pantry in Chattogram | Lucky Store',
    titleBn: 'ফ্রেশ চিনি, তেল ও নিত্যপণ্য চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Buy Fresh refined sugar, pure soybean oil, salt & pantry staples online from Lucky Store in Chawkbazar, Chattogram.',
    descBn: 'চট্টগ্রামের চকবাজারে লাকি স্টোর থেকে ফ্রেশ সাদা চিনি, আয়োডিনযুক্ত লবণ ও ভোজ্য তেল সহজে কিনুন।',
    badgeEn: 'Purity & Quality',
    badgeBn: 'বিশুদ্ধতা ও মান',
    summaryEn: 'Meghna Group Fresh brand refined sugar, iodized salt, cooking oil, and spices delivered to your home.',
    summaryBn: 'ফ্রেশ ব্র্যান্ডের প্যাকেটজাত চিনি, লবণ এবং মসলা ঘরে বসে অনলাইনে অর্ডার করুন।',
  },
  {
    slug: 'ispahani',
    name: 'Ispahani',
    bengaliName: 'ইস্পাহানি',
    searchQuery: 'Ispahani',
    titleEn: 'Ispahani Mirzapore Tea & Blends in Chattogram | Lucky Store',
    titleBn: 'ইস্পাহানি মির্জাপুর চা চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Order fresh Ispahani Mirzapore Best Leaf, Black Tea & Blender\'s Choice from Lucky Store in Chattogram. Same-day local delivery.',
    descBn: 'চট্টগ্রামে আসল ইস্পাহানি মির্জাপুর বেস্ট লিফ ও ব্লেন্ডারস চয়েস চা অনলাইনে কিনুন লাকি স্টোরে।',
    badgeEn: 'Chittagong Heritage Tea',
    badgeBn: 'ঐতিহ্যবাহী সেরা চা',
    summaryEn: 'Bangladesh\'s premier tea brand Ispahani Mirzapore fresh premium tea bags and bulk leaf blends delivered in peak aroma.',
    summaryBn: 'চট্টগ্রামের ঐতিহ্যবাহী ইস্পাহানি মির্জাপুর চা ও প্রিমিয়াম টি ব্যাগ সরাসরি ঘরে পৌঁছে দেওয়া হচ্ছে।',
  },
  {
    slug: 'polar',
    name: 'Polar',
    bengaliName: 'পোলার',
    searchQuery: 'Polar',
    titleEn: 'Polar Ice Cream & Frozen Desserts in Chattogram | Lucky Store',
    titleBn: 'পোলার আইসক্রিম ও ফ্রোজেন ডেজার্ট চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Indulge in Polar ice cream tubs, cones, chocobars & kulfi delivered cold to your doorstep in Chawkbazar, Chattogram.',
    descBn: 'চকবাজার ও আশেপাশের এলাকায় পোলার কাপ, কোন, চকবার ও কুলফি আইসক্রিম বরফ শীতল অবস্থায় হোম ডেলিভারি নিন।',
    badgeEn: 'Chilled & Frozen Delivery',
    badgeBn: 'বরফ শীতল ডেলিভারি',
    summaryEn: 'Creamy Polar vanilla, chocolate, mango, and sundae ice cream delivered with proper cold insulation right to your doorstep.',
    summaryBn: 'পোলার ব্র্যান্ডের সুস্বাদু চকবার, কোন এবং ১ লিটার ফ্যামিলি প্যাক আইসক্রিম কিনুন লাকি স্টোরে।',
  },
  {
    slug: 'igloo',
    name: 'Igloo',
    bengaliName: 'ইগলু',
    searchQuery: 'Igloo',
    titleEn: 'Igloo Ice Cream & Treats in Chattogram | Lucky Store',
    titleBn: 'ইগলু আইসক্রিম চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Order Igloo ice cream tubs, premium cones, chocobars & sandwiches from Lucky Store in Chattogram. Guaranteed frozen on arrival.',
    descBn: 'লাকি স্টোর থেকে ইগলু প্রিমিয়াম আইসক্রিম, কোন ও কুলফি বরফ জমাট অবস্থায় ঘরে ডেলিভারি পান।',
    badgeEn: 'Pure Dairy Ice Cream',
    badgeBn: 'খাঁটি ডেইরি আইসক্রিম',
    summaryEn: 'Rich Igloo ice cream varieties perfect for hot afternoons and family desserts, delivered fast within 1 km.',
    summaryBn: 'ইগলু আইসক্রিমের হরেক রকমের স্বাদ ও ফ্যামিলি প্যাক অনলাইনে অর্ডার করুন।',
  },
  {
    slug: 'nestle',
    name: 'Nestlé',
    bengaliName: 'নেসলে',
    searchQuery: 'Nestle',
    titleEn: 'Nestlé, Maggi & Nescafé in Chattogram | Lucky Store',
    titleBn: 'নেসলে, ম্যাগি ও নেসক্যাফে চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Shop Maggi 2-Minute Noodles, Nescafé Classic Coffee, Nido Milk & KitKat from Lucky Store in Chattogram with Cash on Delivery.',
    descBn: 'চট্টগ্রামের চকবাজারে লাকি স্টোর থেকে ম্যাগি নুডলস, নেসক্যাফে কফি, নিডো দুধ ও কিটক্যাট কিনুন।',
    badgeEn: 'Global Nutrition & Taste',
    badgeBn: 'সেরা স্বাদ ও পুষ্টি',
    summaryEn: 'Original Nestlé groceries: Maggi noodles and masala, Nescafé rich coffee, Coffee-Mate, and Nido fortified milk powder.',
    summaryBn: 'আসল ম্যাগি নুডলস, নেসক্যাফে কফি ও নিডো দুধ ঘরে বসেই দ্রুত ডেলিভারি পান।',
  },
  {
    slug: 'pran',
    name: 'Pran',
    bengaliName: 'প্রাণ',
    searchQuery: 'Pran',
    titleEn: 'Pran Spices, Snacks & Pantry Foods in Chattogram | Lucky Store',
    titleBn: 'প্রাণ মসলা, স্ন্যাক্স ও খাদ্যপণ্য চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Browse Pran spices, biscuits, toast, drinks & culinary staples online at Lucky Store in Chawkbazar, Chattogram.',
    descBn: 'প্রাণ ব্র্যান্ডের মসলা, টোস্ট বিস্কুট, চানাচুর ও জুস লাকি স্টোর থেকে অনলাইনে অর্ডার করুন।',
    badgeEn: 'Household Favorites',
    badgeBn: 'জনপ্রিয় খাদ্যপণ্য',
    summaryEn: 'Everyday pantry and snacking options from Pran, delivered swiftly across the Chawkbazar neighborhood.',
    summaryBn: 'প্রাণ এর হরেক রকমের শুকনো খাবার, মসলা ও ডেইরি আইটেম সহজে কিনুন।',
  },
  {
    slug: 'dove',
    name: 'Dove',
    bengaliName: 'ডাভ',
    searchQuery: 'Dove',
    titleEn: 'Dove Beauty Bars, Shampoos & Care in Chattogram | Lucky Store',
    titleBn: 'ডাভ বিউটি বার, শ্যাম্পু ও প্রসাধন চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Shop genuine Dove moisturizing beauty bars, intense repair shampoos & conditioners in Chattogram from Lucky Store.',
    descBn: 'আসল ডাভ ময়েশ্চারাইজিং সাবান, শ্যাম্পু ও কন্ডিশনার লাকি স্টোরে ঘরে বসেই অর্ডার করুন।',
    badgeEn: 'Gentle Moisturizing Care',
    badgeBn: 'কোমল ত্বকের যত্ন',
    summaryEn: 'Authentic Dove gentle skin cleansing bars and hair care products with 1/4 moisturizing cream.',
    summaryBn: 'ডাভ বিউটি বার এবং হেয়ার কেয়ার পণ্য ডোরস্টেপ চেকিং এর সুবিধাসহ ডেলিভারি নিন।',
  },
  {
    slug: 'lux',
    name: 'Lux',
    bengaliName: 'লাক্স',
    searchQuery: 'Lux',
    titleEn: 'Lux Fragrant Beauty Soap in Chattogram | Lucky Store',
    titleBn: 'লাক্স সুগন্ধি সাবান চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Order Lux beauty soap bars & body washes with floral fragrances from Lucky Store in Chattogram. Same-day delivery.',
    descBn: 'লাক্স সুবাসিত গ্লিসারিন ও পারফিউম সাবান লাকি স্টোর থেকে অনলাইনে কিনুন।',
    badgeEn: 'Floral Fragrance Soaps',
    badgeBn: 'সুগন্ধি রূপচর্চা',
    summaryEn: 'Lux beauty soap bars with essential oils and floral infusions for daily refreshing skincare.',
    summaryBn: 'লাক্স বিউটি সাবানের বিভিন্ন ভ্যারিয়েন্ট ঘরে বসেই অর্ডার করুন।',
  },
  {
    slug: 'sunsilk',
    name: 'Sunsilk',
    bengaliName: 'সানসিল্ক',
    searchQuery: 'Sunsilk',
    titleEn: 'Sunsilk Shampoos & Hair Conditioners in Chattogram | Lucky Store',
    titleBn: 'সানসিল্ক শ্যাম্পু ও হেয়ার কেয়ার চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Buy Sunsilk Black Shine, Thick & Long, and Hairfall Solution shampoos in Chattogram from Lucky Store.',
    descBn: 'সানসিল্ক ব্ল্যাক শাইন এবং হেয়ারফল সল্যুশন শ্যাম্পু চকবাজার লাকি স্টোরে সহজলভ্য।',
    badgeEn: 'Hair Care Solutions',
    badgeBn: 'চুলের যত্ন',
    summaryEn: 'Popular Sunsilk shampoos and hair nourishing solutions available in multiple bottle sizes.',
    summaryBn: 'সানসিল্ক ব্র্যান্ডের শ্যাম্পুর বিভিন্ন সাইজ ঘরে বসেই ডেলিভারি নিন।',
  },
  {
    slug: 'dettol',
    name: 'Dettol',
    bengaliName: 'ডেটল',
    searchQuery: 'Dettol',
    titleEn: 'Dettol Antiseptic, Soap & Hygiene in Chattogram | Lucky Store',
    titleBn: 'ডেটল অ্যান্টিসেপ্টিক ও সাবান চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Keep your home protected with Dettol antiseptic liquid, hand wash & soap bars from Lucky Store in Chattogram.',
    descBn: 'আসল ডেটল অ্যান্টিসেপটিক লিকুইড, হ্যান্ডওয়াশ ও সাবান লাকি স্টোরে কিনুন।',
    badgeEn: 'Germ Protection',
    badgeBn: 'জীবাণু সুরক্ষা',
    summaryEn: 'Trusted Dettol personal protection and hygiene supplies for families in Chawkbazar.',
    summaryBn: 'পরিবারের সুরক্ষায় ডেটল লিকুইড এবং সাবান অনলাইনে অর্ডার করুন।',
  },
  {
    slug: 'bashundhara',
    name: 'Bashundhara',
    bengaliName: 'বসুন্ধরা',
    searchQuery: 'Bashundhara',
    titleEn: 'Bashundhara Tissue & Household Paper in Chattogram | Lucky Store',
    titleBn: 'বসুন্ধরা টিস্যু ও পেপার পণ্য চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Order Bashundhara facial tissue, toilet tissue, kitchen towels & napkins from Lucky Store in Chattogram.',
    descBn: 'বসুন্ধরা ফেসিয়াল টিস্যু, টয়লেট রোল ও কিচেন টাওয়েল সাশ্রয়ী মূল্যে ঘরে বসেই পান।',
    badgeEn: 'Soft & Hygienic Paper',
    badgeBn: 'কোমল ও স্বাস্থ্যকর পেপার',
    summaryEn: 'Bashundhara hygienic paper products and daily household cleaning paper delivered straight to your door.',
    summaryBn: 'বসুন্ধরা টিস্যু পেপারের যাবতীয় সাইজ ও ভ্যারাইটি ঘরে বসেই ডেলিভারি নিন।',
  },
  {
    slug: 'olympic',
    name: 'Olympic',
    bengaliName: 'অলিম্পিক',
    searchQuery: 'Olympic',
    titleEn: 'Olympic Biscuits, Cookies & Bakery in Chattogram | Lucky Store',
    titleBn: 'অলিম্পিক বিস্কুট ও ড্রাই কেক চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Shop Olympic Energy Plus, Nutty, Tip & dry cake snacks online from Lucky Store in Chawkbazar, Chattogram.',
    descBn: 'অলিম্পিক এনার্জি প্লাস, কুকিজ ও চানাচুর লাকি স্টোর থেকে অনলাইনে অর্ডার করুন।',
    badgeEn: 'Crispy Tea-Time Biscuits',
    badgeBn: 'চায়ের আড্ডার বিস্কুট',
    summaryEn: 'Olympic crispy biscuits and tea-time bakery treats available in fresh stock.',
    summaryBn: 'অলিম্পিক বিস্কুট ও হালকা নাস্তার সেরা আইটেম অনলাইনে সহজে কিনুন।',
  },
  {
    slug: 'fortune',
    name: 'Fortune',
    bengaliName: 'ফরচুন',
    searchQuery: 'Fortune',
    titleEn: 'Fortune Foods & Specialty Products in Chattogram | Lucky Store',
    titleBn: 'ফরচুন ফুডস ও স্পেশাল পণ্য চট্টগ্রাম | লাকি স্টোর',
    descEn: 'Order Fortune culinary products and Fortune Cookies from Lucky Store in Chawkbazar, Chattogram.',
    descBn: 'লাকি স্টোর থেকে ফরচুন পণ্য ও ফরচুন কুকিজ অনলাইনে কিনুন। দ্রুত হোম ডেলিভারি।',
    badgeEn: 'Premium Quality Foods',
    badgeBn: 'উন্নত মানের খাবার',
    summaryEn: 'Premium Fortune food products and localized fortune treats backed by doorstep verification.',
    summaryBn: 'ফরচুন ফুডস এবং ফ্রেশ পণ্যের কালেকশন লাকি স্টোরে সহজলভ্য।',
  },
] as const;

export function getBrandBySlug(slug: string): BrandDefinition | undefined {
  const norm = slug.toLowerCase().trim();
  return POPULAR_BRANDS.find((b) => b.slug === norm);
}

export function getAllBrandSlugs(): string[] {
  return POPULAR_BRANDS.map((b) => b.slug);
}
